### PR TITLE
Added donation addresses + Cryptonator no longer uses hardcoded values + Dashcoin example

### PR DESCRIPTION
**Pull request by pmitchev**
- Added donation addresses for core developers
- Cryptonator widget now uses "symbol" from server config
- Dashcoin config example

### CODE REVIEW

**Comment by fancoder** [comment]
Hi

You should always separate Pull request with different features :)
1. I can accept coreDevDonation` wallets only from @zone117 because I'm not sure that you was in pool core developers team
2. Config example for different coins should be stored in separate chapter, in README.md there are only 4 options you can customize to help pool ops to configure pool for some coin http://i.imgur.com/SAI36VW.png You can add this chapter before https://github.com/fancoder/cryptonote-universal-pool/blob/master/README.md#3-optional-configure-cryptonote-easy-miner-for-your-pool
3. Cryptonator auto config is great idea, but if you want me to accept it, please create new Pull request.

**Comment by pmitchev** [comment]
My first pool request :) I will correct the issues.
About 2. : there is a hidden option, different for every coin - min TX fee.

**Comment by pmitchev** [comment]
Isn't coreDevDonation for coin devs? I will add link from where I got the addresses in the pull request.

**Comment by fancoder** [comment]
I think coreDevDonation is for pool core developers. Coin developers usually got donations by itself, when they do pre-mining and then just gowing up coin price :) Am i wrong?

**Comment by fancoder** [comment]
> About 2. : there is a hidden option, different for every coin - min TX fee.

Yes, sure. There are also 80-33 lined with coin-specified options. https://github.com/fancoder/cryptonote-universal-pool/blob/master/config.json#L80

**Pull request closed without merging**
